# Generated by Django 5.2.12 on 2026-06-11 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rol', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='rol',
            table='rol',
        ),
        migrations.AlterModelTable(
            name='rolmenu',
            table='rol_menu',
        ),
    ]
