# Generated by Django 5.2.12 on 2026-06-05 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoMovimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.IntegerField(choices=[(1, 'Ingreso'), (2, 'Salida')])),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo de Movimiento',
                'verbose_name_plural': 'Tipos de Movimientos',
                'ordering': ['tipo', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Kardex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_interno', models.CharField(max_length=20)),
                ('codigo_barra', models.CharField(blank=True, max_length=100)),
                ('nombre_producto', models.CharField(max_length=250)),
                ('cantidad', models.IntegerField()),
                ('stock_anterior', models.IntegerField()),
                ('stock_nuevo', models.IntegerField()),
                ('precio_costo', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('precio_venta', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('subtotal', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('correlativo_referencia', models.CharField(blank=True, max_length=50)),
                ('id_venta', models.IntegerField(blank=True, null=True)),
                ('detalle_venta_id', models.IntegerField(blank=True, null=True)),
                ('fecha_movimiento', models.DateTimeField(auto_now_add=True)),
                ('usuario_id', models.IntegerField()),
                ('origen_movimiento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='kardex.tipomovimiento')),
            ],
            options={
                'ordering': ['-fecha_movimiento'],
            },
        ),
    ]
