# Generated by Django 5.2.12 on 2026-06-06 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kardex', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kardex',
            old_name='precio_costo',
            new_name='precio_compra',
        ),
    ]
