# Generated by Django 5.2.12 on 2026-06-11 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kardex', '0002_rename_precio_costo_to_precio_compra'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='kardex',
            table='kardex',
        ),
        migrations.AlterModelTable(
            name='tipomovimiento',
            table='kardex_tipo_movimiento',
        ),
    ]
