# Generated by Django 5.2.12 on 2026-06-11 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='menu',
            table='menu',
        ),
    ]
