# Generated by Django 5.2.12 on 2026-06-04 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('id_venta', models.IntegerField()),
                ('descripcion_producto', models.CharField(max_length=255)),
                ('codigo_barra', models.CharField(max_length=100)),
                ('cantidad_venta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sub_total_venta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado_venta', models.IntegerField(choices=[(1, 'Pagado'), (2, 'Devolucion Parcial'), (3, 'Devolucion Total')], default=1)),
                ('devolucion_cantidad', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('devolucion_monto', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('devolucion_fecha', models.DateTimeField(blank=True, null=True)),
                ('usuario_actualizacion', models.IntegerField(blank=True, null=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id_venta', models.AutoField(primary_key=True, serialize=False)),
                ('correlativo_venta', models.CharField(max_length=20, unique=True)),
                ('fecha_venta', models.DateTimeField()),
                ('id_usuario_venta', models.IntegerField()),
                ('total_venta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado_venta', models.IntegerField(choices=[(1, 'Pagado'), (2, 'Devolucion Parcial'), (3, 'Devolucion Total')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='VentaPago',
            fields=[
                ('id_pago', models.AutoField(primary_key=True, serialize=False)),
                ('id_venta', models.IntegerField()),
                ('forma_pago', models.IntegerField(choices=[(1, 'Efectivo'), (2, 'Yape'), (3, 'Tarjeta'), (4, 'Transferencia')])),
                ('monto_pagar', models.DecimalField(decimal_places=2, max_digits=10)),
                ('efectivo_recibido', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('efectivo_vuelto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fecha_pago', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
