# Generated by Django 5.2.12 on 2026-06-05 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleventa',
            name='codigo_interno',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
