# Generated by Django 5.2.12 on 2026-06-05 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0002_detalleventa_codigo_interno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='correlativo_venta',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
