# Generated by Django 5.2.12 on 2026-06-11 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0003_alter_venta_correlativo_venta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleventa',
            name='fecha_actualizacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
