# Generated by Django 5.2.12 on 2026-06-11 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0004_alter_detalleventa_fecha_actualizacion'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='detalleventa',
            table='venta_detalle',
        ),
        migrations.AlterModelTable(
            name='venta',
            table='venta',
        ),
        migrations.AlterModelTable(
            name='ventapago',
            table='venta_tipo_pago',
        ),
    ]
