# Generated by Django 5.2.12 on 2026-06-03 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=500)),
                ('cantidad_producto', models.IntegerField(default=0)),
                ('costo_producto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('codigo_barra', models.CharField(blank=True, max_length=100)),
                ('estado', models.BooleanField(default=True)),
                ('usuario_creacion', models.IntegerField(blank=True, null=True)),
                ('usuario_actualizacion', models.IntegerField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
