# Generated by Django 5.2.12 on 2026-06-05 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0002_alter_producto_nombre_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='codigo_interno',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True),
        ),
    ]
