# Generated by Django 5.2.12 on 2026-06-05 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0003_producto_codigo_interno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='codigo_interno',
            field=models.CharField(blank=True, default='TEMPORAL', editable=False, max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
