# Generated by Django 5.2.12 on 2026-06-11 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0004_alter_producto_codigo_interno'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='producto',
            table='producto',
        ),
    ]
