# Generated by Django 5.2.12 on 2026-06-11 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usuariomenu',
            table='usuario_menu',
        ),
        migrations.AlterModelTable(
            name='usuariorol',
            table='usuario_rol',
        ),
    ]
